# Generated by Django 4.1.2 on 2022-11-17 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_product_wishlist_alter_userprofile_purchased'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasedField', models.ManyToManyField(related_name='myproduct', to='myapp.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
