# Generated by Django 4.1 on 2022-09-29 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='affiliate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='myapp.store'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
