# Generated by Django 4.1.2 on 2022-11-17 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_userprofile2'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile2',
            name='admin',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
