# Generated by Django 4.1.2 on 2022-11-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userprofile2_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile2',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlists', to='myapp.product'),
        ),
    ]
